## Task 1: Data Cleaning & Preprocessing
**Dataset:** Titanic Dataset  
**Objective:**  
Clean and prepare raw data for analysis  
**Tasks:**
- Handle missing values
- Remove duplicates
- Convert data types
- Rename columns
**Output:**
Clean dataset ready for analysis

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset('titanic')

In [3]:
# Project Setup 
print("First Five rows of titanic dataset")
df.head()

First Five rows of titanic dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
print("Random Five rows")
df.sample(5)

Random Five rows

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
776,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,F,Queenstown,no,True
414,1,3,male,44.0,0,0,7.9250,S,Third,man,True,NaN,Southampton,yes,True
296,0,3,male,23.5,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
786,1,3,female,18.0,0,0,7.4958,S,Third,woman,False,NaN,Southampton,yes,True
519,0,3,male,32.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True

In [5]:
print("Last Five rows")
df.tail()

Last Five rows

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
print("Columns of titanic dataset")
print(df.columns.to_list())

print(f"Titanic dataset have {df.shape[0]} rows x {df.shape[1]} columns")

Columns of titanic dataset
['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']
Titanic dataset have 891 rows x 15 columns

In [7]:
print("Dataset Information")
df.info()

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [8]:
print("Basic statistical summary of numerical columns")
df.describe()

Basic statistical summary of numerical columns

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

#### Handle Missing Values

In [9]:
#Handle Missing Values
missing_values = df.isna().sum()
print("Total number of missing values in each columns")
print(missing_values)

print()
print("Column that have the most missing data is: ")
col_name = missing_values.sort_values(ascending=False).index[0] 
col_val = missing_values.sort_values(ascending=False).iloc[0]
print(f"{col_name} : {col_val}")

Total number of missing values in each columns
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Column that have the most missing data is:
deck : 688

In [10]:

missing_pct = (df.isna().sum() / len(df) * 100).round(2)
print(pd.DataFrame({'Missing Count': missing_values, 'Missing %': missing_pct}))

             Missing Count  Missing %
survived                 0       0.00
pclass                   0       0.00
sex                      0       0.00
age                    177      19.87
sibsp                    0       0.00
parch                    0       0.00
fare                     0       0.00
embarked                 2       0.22
class                    0       0.00
who                      0       0.00
adult_male               0       0.00
deck                   688      77.22
embark_town              2       0.22
alive                    0       0.00
alone                    0       0.00

In [11]:
# Filling missing age with median over mean because meadian gives middle value 
df['age'] = df['age'].fillna(df['age'].median())

# Filling missing values in embarked and embark_town with the mode (most frequent value).
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

#Droping the deck column
print("The deck column has too many missing values.")
print(f"Among {df.shape[0]} rows deck column have {df.isna().sum().loc['deck']} missing values")
print("Droping the deck column")

df.drop(columns=['deck'], inplace=True)

The deck column has too many missing values.
Among 891 rows deck column have 688 missing values
Droping the deck column

In [12]:
print("Handled missing values successfully")

df.isna().sum()

Handled missing values successfully

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

#### Remove Duplicates

In [13]:
print(f"There are {df.duplicated().sum()} Duplicate rows in titanic dataset")
print("Droping the duplicate rows")

df.drop_duplicates(inplace=True)

print("New Shape of the dataset after the removal of duplicate rows")
print(f"{df.shape[0]} rows x {df.shape[1]} columns")

There are 116 Duplicate rows in titanic dataset
Droping the duplicate rows
New Shape of the dataset after the removal of duplicate rows
775 rows x 14 columns

#### Convert Data Types

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     775 non-null    int64
 1   pclass       775 non-null    int64
 2   sex          775 non-null    object
 3   age          775 non-null    float64
 4   sibsp        775 non-null    int64
 5   parch        775 non-null    int64
 6   fare         775 non-null    float64
 7   embarked     775 non-null    object
 8   class        775 non-null    category
 9   who          775 non-null    object
 10  adult_male   775 non-null    bool
 11  embark_town  775 non-null    object
 12  alive        775 non-null    object
 13  alone        775 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 75.1+ KB

In [15]:
#Converting survived column from integer to a proper categorical type.
print("Data type of survived column:", df['survived'].dtype)
df['survived'] = df['survived'].astype('category')
print("After conversion dtype:", df['survived'].dtype)

# Converting pclass and sex columns to category dtype.
df['pclass'] = df['pclass'].astype('category')
df['sex'] = df['sex'].astype('category')

#checking and converting age,fare to float64
for col in ['age', 'fare']:
    if df[col].dtype != 'float64':
        df[col] = df[col].astype('float64')
print("age and fare dtypes confirmed:", df['age'].dtype, df['fare'].dtype)

Data type of survived column: int64
After conversion dtype: category
age and fare dtypes confirmed: float64 float64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     775 non-null    category
 1   pclass       775 non-null    category
 2   sex          775 non-null    category
 3   age          775 non-null    float64
 4   sibsp        775 non-null    int64
 5   parch        775 non-null    int64
 6   fare         775 non-null    float64
 7   embarked     775 non-null    object
 8   class        775 non-null    category
 9   who          775 non-null    object
 10  adult_male   775 non-null    bool
 11  embark_town  775 non-null    object
 12  alive        775 non-null    object
 13  alone        775 non-null    bool
dtypes: bool(2), category(4), float64(2), int64(2), object(4)
memory usage: 59.5+ KB

#### Rename Columns & Final Check

In [17]:
df.columns.to_list()

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'embark_town',
 'alive',
 'alone']

In [18]:
# Rename sibsp → siblings_spouses and parch → parents_children.

df.rename(columns= {
    'sibsp' : 'siblings_spouses', 
    'parch' : 'parents_children'
 }, inplace=True)

df.columns

Index(['survived', 'pclass', 'sex', 'age', 'siblings_spouses',
       'parents_children', 'fare', 'embarked', 'class', 'who', 'adult_male',
       'embark_town', 'alive', 'alone'],
      dtype='object')

In [19]:
# Final Check 
print("Final missing values check:")
print(df.isna().sum())
print("Final duplicate check:", df.duplicated().sum())

Final missing values check:
survived            0
pclass              0
sex                 0
age                 0
siblings_spouses    0
parents_children    0
fare                0
embarked            0
class               0
who                 0
adult_male          0
embark_town         0
alive               0
alone               0
dtype: int64
Final duplicate check: 0

In [20]:
# Saving the cleaned dataset as titanic_cleaned.csv for EDA 

df.to_csv('titanic_cleaned.csv', index=False)